name: CI - build, push and merge with scip

on:
  push:
    branches: [ "python3*" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build'
        required: true

permissions:
  contents: write
  actions: write

jobs:
  build-python:
    name: Build python multi arch
    uses: ./.github/workflows/ci-build-and-push.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      python_version: 3.14.7
      tag: 3.14.7
      dockerfile: ./python-build.dockerfile

  merge-manifest-python:
    name: merge manifest multi arch python
    uses: ./.github/workflows/ci-merge-manifest.yml
    needs: [ build-python ]
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      tag: 3.14.0

  build-scip:
    name: Build scip multi arch
    needs: [ merge-manifest-python ]
    uses: ./.github/workflows/ci-build-and-push.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      python_version: 3.14.7
      tag: 3.14.7-scip
      dockerfile: ./python-scip.dockerfile

  merge-manifest-scip:
    name: merge manifest multi arch scip
    needs: [ build-scip ]
    uses: ./.github/workflows/ci-merge-manifest.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      tag: 3.14.7-scip