name: CI - build and push docker image

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to build'
        required: true
        type: string
      python_version:
        description: 'python version to build'
        required: true
        type: string
      tag:
        description: 'docker tag to push'
        required: true
        type: string
      dockerfile:
        description: 'Docker file to build'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build'
        required: true
        type: string
      python_version:
        description: 'python version to build'
        required: true
        type: string
      tag:
        description: 'docker tag to push'
        required: true
        type: string
      dockerfile:
        description: 'Docker file to build'
        required: true
        type: string


permissions:
  contents: write
  actions: write


jobs:
  build-multi-arch:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-${{ matrix.arch }}
      cancel-in-progress: true
    name: build ${{ matrix.arch }} ${{ inputs.dockerfile }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 300
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: "linux/amd64"
            arch: "amd64"
            runner: "ubuntu-latest"
          - platform: "linux/arm/v7"
            arch: "armv7l"
            runner: "ubuntu-24.04-arm"
          - platform: "linux/arm64"
            arch: "arm64"
            runner: "ubuntu-24.04-arm"
    steps:
      - name: Collect Workflow Telemetry
        if: ${{ !env.ACT }}
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - uses: actions/checkout@v4
        if: ${{ !env.ACT }}
        with:
          repository: pich02/python-docker-builder
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}
          cache-image: true

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}
          cache-binary: true

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: Build

      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: cache-mount
          key: cache-mount-${{ hashFiles('${{ inputs.dockerfile }}') }}

      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cache-mount
          dockerfile: ${{ inputs.dockerfile }}
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: pich02/python3-glibc2.24:${{ inputs.tag }}-${{ matrix.arch }}
          platforms: ${{ matrix.platform }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ inputs.dockerfile }}
          build-args: |
            PYTHON_VERSION=${{ inputs.python_version }}
